apiVersion: v1
kind: Secret
metadata:
  name: geoserver-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GEOSERVER_DATA_DIR: {{ .Values.dataDir }}
  GEOSERVER_ADMIN_USER: {{ .Values.adminCredentials.userName }}
  GEOSERVER_ADMIN_PASSWORD: {{ .Values.adminCredentials.password }}
  COMMUNITY_EXTENSIONS: {{ .Values.plugins.community }}
  STABLE_EXTENSIONS: {{ .Values.plugins.stable }}
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}