apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{.Values.port}}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}