{{ if .Values.backup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.backup.backupStorageSpec.pvc.name}}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{.Values.backup.backupStorageSpec.pvc.storageClassName}}
  volumeName: "{{.Values.backup.backupStorageSpec.volume.name}}"
  accessModes:
    - {{.Values.backup.backupStorageSpec.pvc.accessMode}}
  resources:
    requests:
      storage: {{.Values.backup.backupStorageSpec.pvc.storage}}
{{ end }}
