apiVersion: v1
kind: ConfigMap
metadata:
  name: geoserver-config-readonly
  namespace: {{ .Release.Namespace }}
binaryData:
  {{ range $path, $bytes := .Files.Glob (printf "data/**")}}
  {{ $name := base $path }}
  {{- sha256sum (printf "%s/%s" (index (regexSplit "^data" (dir $path) -1) 1 ) $name ) | indent 2 }}{{ print ": "}}{{ $.Files.Get $path | b64enc | quote }}
  {{ end }}